---
version: '2'
services:
  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:4.0.0
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 192.168.99.100:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry 
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
  
  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest:4.0.0
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    environment:  
      KAFKA_REST_ZOOKEEPER_CONNECT: 192.168.99.100:2181
      KAFKA_REST_LISTENERS: http://kafka-rest:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_HOST_NAME: kafka

  kafka-topics:
    container_name: kafka-topics
    image: landoop/kafka-topics-ui:latest
    depends_on:
      - zookeeper
      - kafka
      - kafka-rest
      - schema-registry
    ports:
      - 8000:8000
    environment:
      KAFKA_REST_PROXY_URL: kafka-rest:8082
      PROXY: 'true'


  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    ports:
      - 2181:2181    
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 192.168.99.100:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.100:29092,PLAINTEXT_HOST://192.168.99.100:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1